name: publish
on:
  push:
    tags:
     - 'v*'

jobs:
  publish-tag:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.10

      - name: Build source and wheel distributions
        run: |
          uv build
          uv run twine check dist/*

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
